### ISSUE TITLE
Swipe on the video

### ISSUE THREAD

**Issue by fornyhucker** [yairEO/photobox#101]
Hi! In Photobox you can change photo with swipe even on the photo itself. With videos it doesn't happen. I don't figure out why but i think is something related to the generated iframe. The swipe this time works only out of the iframe indeed. Any workaround?

Thanks!

**Comment by yairEO** [comment]
unfortunately I know of no way to do so. the video is above everything, so all the browser events (like touch) does not work on the video area.
