### ISSUE TITLE
Is there some one who can help me in this case? 

### ISSUE THREAD

**Issue by arteconst** [yairEO/photobox#104]
I tried to use  Photobox for representation of my works on my portfolio-page. 
I must say Photobox have very nice functions and design. 

Unfortunately I could not personalize loading my own photos: Yes, I saw a piece of code that is proposed for this purpose, but for me remains a complete mystery WHERE (in what place of which file) this kind code must be inserted - as my profession very far from programing. 
![ss](https://cloud.githubusercontent.com/assets/13789512/9264676/08f884bc-423a-11e5-93c4-070c1d6952e7.jpg)

Is there some one who can help me in this case? 

I don't plan use any image from Flickr and  i want put only my own photos from my hosting and some videos from Youtube.

**Comment by yairEO** [comment]
Well you at least know basic HTML and CSS?

**Comment by arteconst** [comment]
Yes of course BUT
is very precisely said BASIC html & css, I have to add very basic

2015-08-14 15:39 GMT+04:00, vsync <notifications@github.com>:
> Well you at least know basic HTML and CSS?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/yairEO/photobox/issues/104#issuecomment-131084322


-- 
С уважением,
Константин Егоров

**Comment by arteconst** [comment]
If we take your page "Photobox" as a hypothetical example of html code
  after what kind of line number , I'll have to insert the given
example HTML (after i make modifications at  it )?

2015-08-14 16:38 GMT+04:00, Константин Егоров <arteconst@gmail.com>:
> Yes of course BUT
> is very precisely said BASIC html & css, I have to add very basic
>
> 2015-08-14 15:39 GMT+04:00, vsync <notifications@github.com>:
>> Well you at least know basic HTML and CSS?
>>
>> ---
>> Reply to this email directly or view it on GitHub:
>> https://github.com/yairEO/photobox/issues/104#issuecomment-131084322
>
>
> --
> С уважением,
> Константин Егоров
>


-- 
С уважением,
Константин Егоров
