### ISSUE TITLE
Photobox don't work with YouTube

### ISSUE THREAD

**Issue by Guibz12** [yairEO/photobox#109]
https://cloud.githubusercontent.com/assets/15988902/11351172/64ed59f0-9235-11e5-8325-eaee9be3e0a0.jpg
Why Photobox don't working with a link to a YouTube Video ? The player is not displaying !

I have it's error : Load denied by X-Frame-Options: https://www.youtube.com/watch?v=LVn8ei8d4iU&vq=hd720&wmode=opaque does not permit cross-origin framing.

**Comment by yairEO** [comment]
why did you close this issue?

**Comment by yairEO** [comment]
http://stackoverflow.com/a/25661346/104380
