### ISSUE TITLE
first image quickly slides to the left (Safari)

### ISSUE THREAD

**Issue by marathia** [yairEO/photobox#112]
Strange problem with Safari (both on OS X and iOS): when opening the lightbox, the image quickly slides to the left and comes back as normal. When closing and reopening the lightbox again, the problem does not occur again.

NB This also happens on the demo page.

**Comment by jrondorf** [comment]
The same happens for me. This happens for me when displaying photobox the first time and the images are not loaded into the cache (so delete the cache to reproduce the issue).

I already tried to follow some of the advices on http://stackoverflow.com/questions/2946748/iphone-webkit-css-animations-cause-flicker, http://www.bluepiccadilly.com/2012/01/prevent-flickering-css-transitions-and-transforms-webkit but was not able to solve this.

**Comment by marathia** [comment]
Yeah, I tried that too without success. I am no longer convinced it is a CSS problem.

**Comment by yairEO** [comment]
very strange indeed

**Comment by jrondorf** [comment]
I am able to confirm @marathia 's comment. Removing `transition:0.2s;` from `.pbWrapper` removes this strange slide.
