### ISSUE TITLE
Zoom-in is blurry in Chrome

### ISSUE THREAD

**Issue by dabustard** [yairEO/photobox#118]
Look at the working [Jsfiddle](https://jsfiddle.net/1vvch8vw/)
Try to zoom in 1st image in Chrome and than try same in Firefox or IE.
How to fix it?

**Comment by yairEO** [comment]
looks the same to me, but maybe it's because of how Chrome works, it doesn't do "real" scale but only scaling the rendered image and not the "real" image. I'm pretty sure it cannot be fixed. Also, you should have included screenshots of the issue, would have been nicer ;)
