### ISSUE TITLE
Modal doesn't appear

### ISSUE THREAD

**Issue by Pulsari** [yairEO/photobox#123]
I've clearly missed something in my implementation as I am the point where the thumbs appear, but when I click on them, they browser simply navigates to the image - no modal appears. I've created a simple test page to make sure it wasn't a problem with something else on the page, so now I need some guidance. Thank you.
[HtmlPage.txt](https://github.com/yairEO/photobox/files/595435/HtmlPage.txt)

**Comment by yairEO** [comment]
you managed to solve this for yourself?
