### ISSUE TITLE
JQuery appending but not showing

### ISSUE THREAD

**Issue by pankajiitkgp** [yairEO/photobox#126]
On using this jquery appending all the images link but on clicking gallery is not working. I don't know what to do. Please help

$("#g1, #g2").click(function(e) {
      e.preventDefault();
      var e_id, i;
      e_id = $(this).attr("id");
      console.log(e_id);
      for( i = 2; i < 5; i++){
        $('#'+ e_id +'').append('html tag with a link and img source');
      }
    });

**Comment by yairEO** [comment]
please provide a demo page or any page where I can see the problem happening

**Comment by pankajiitkgp** [comment]
Here is the Demo page: https://pankajiitkgp.github.io/gallery/

I want a gallery type of page, where I will have different card for
different albums. On clicking one card it will show only the photos related
to that album.
On using the blow code, jquery appending all the images link but on
clicking gallery is not working. I don't know what to do. Please help.

<script type="text/javascript">
$('#g1').photobox('a',{ thumbs:true, loop:false });
    $('#g2').photobox('a',{ thumbs:true, loop:false });
$("#g1, #g2").click(function(e) {
      e.preventDefault();
      var e_id, i;
      e_id = $(this).attr("id");
      console.log(e_id);
      for( i = 2; i < 5; i++){
        $('#'+ e_id +'').append('<a href="images/'+ e_id +'/r-('+ i
+').jpg"><img class="card-img cd-hide" src="images/'+ e_id +'/r-('+ i
+').jpg" title=""></a>');
      }
    });
</script>


Regards,

Pankaj Sarkar
Final Year Undergraduate Student
Civil Engineering Department,
Indian Institute of Technology, Kharagpur

Email ID: pankajsarkar@iitkgp.ac.in
Contact No.: (+91) 9932668593

**Comment by pankajiitkgp** [comment]
Dear Sir,

I have attached two screenshots of the page after inspecting element. The
image with name "First Shot" is just after loading the page where it only
showing the link of only one photo. Whereas the "Second shot" is after
clicking one album, now in inspect element window, it showing all the link.

Hope you got my problem.

**Comment by yairEO** [comment]
gallery is working fine on your demo page... 

testing on `Chrome Version 58.0.3029.110 (64-bit)`
