### ISSUE TITLE
image gallery - have you seen anything like this

### ISSUE THREAD

**Issue by eddyparkinson** [yairEO/photobox#127]
I am looking for an image gallery that works on mobile. This is $50 per month, which is fine, but it

 does not have options we need (fails with over 8000 images and we need a search filter that includes "OR" not just "AND")

https://betapromology.myshopify.com/pages/there-it-is

Have you seen anything that might work. We need a way to get issues fixed, so open source, or an ongoing maintenance fee would be better.

**Comment by yairEO** [comment]
I don't understand your question. are you asking me to recommend you some random image gallery other than my own?

**Comment by eddyparkinson** [comment]
Yes. , I want to know about strengths of different Image Galleries.  I found several, but looks like the search is the big problem, as searching 40,000 items is hard, much harder than I expect.

**Comment by yairEO** [comment]
I don't know any other galleries.. :) really don't.
This code is quite old, I would re-write it all today if I had but, BUT it still beats the shit out of other gallery code I bet. it's quite efficient. just a bit messy, but not a lot of code lines at all! does the job excellent. very easy to customize..
