### ISSUE TITLE
Preview for huge files failing in Chrome

### ISSUE THREAD

**Issue by praveenmungara1921988** [yairEO/photobox#142]
Hi,

Thumbnails and actual photos are not showing up in chrome for images of about ~8 MB size or more. 

Thanks & Regards,

Praveen Mungara
![photobox_issue](https://user-images.githubusercontent.com/39499756/40325457-671b81c2-5d01-11e8-91fd-215e2c9f3ac3.jpg)

**Comment by yairEO** [comment]
This is an image-viewer-only script and gallery related issues has nothing to do with photobox.
