### ISSUE TITLE
Observer in ie8

### ISSUE THREAD

**Issue by TrySound** [yairEO/photobox#82]
DOM Observer doesn't work in ie8. Have an error in IETester
```
Line: 183
Column: 17
Object doesn't support this property or method
```

**Comment by yairEO** [comment]
I think I might drop IE8 support, or at least make this plugin "functional enough" for basic use. Testing for IE8 requires me to boot up a virtual machine and test there, which is time demanding.

Thanks for reporting! sorry for being slow. so many things needs to be done all the time..

**Comment by TrySound** [comment]
@yairEO Woo-hoo! No IE8!
