### ISSUE TITLE
SASS Vendor Prefixes

### ISSUE THREAD

**Issue by TrySound** [yairEO/photobox#84]
SASS extends verndor prefixes with bad order
Prefixed properties must be in the beginning.

**Comment by TrySound** [comment]
And formatting looks uncomfortable

**Comment by TrySound** [comment]
You may use autoprefixer.

**Comment by yairEO** [comment]
what are you talking about? there is no SCSS file in this project, only css

**Comment by TrySound** [comment]
You told me that SCSS compile this. So, it is responding for prefixes. In result css: transform:
```css
transform:scale(0) rotateX(80deg);
-webkit-transform:scale(0) rotateX(80deg);
-ms-transform:scale(0) rotateX(80deg);
```

Unprefixed declaration must be after all prefixed declarations.

**Comment by yairEO** [comment]
well, I am planning on getting rid of all that CSS and create a new `SCSS` file which would be easier to manage... I am flooded with work currently don't have the time to do so, but I will soon. I am working with Photobox on a daily basis and extended it far beyond what is presented in this repository. It's a very flexible system and converting the CSS to SCSS would take it a nice step forward

**Comment by TrySound** [comment]
Okey! Waiting for next release. Hope my pull request was useful.
