### ISSUE TITLE
rel="group"

### ISSUE THREAD

**Issue by mindochin** [yairEO/photobox#88]
is it possible to split the photo in groups and show photo in their group only? (aka rel="group" in fancybox)

**Comment by yairEO** [comment]
Not really, but I can make it I guess. Now you must bind photobox into different containers, because each container has tons of logic connected to it and currently cannot support multiple photobox settings (like groups). you will have to create separate containers and bind photobox to them:

    $('ul.group1').photobox('a');
    $('ul.group2').photobox('a');
    // or
    $('ul[rel=group3]').photobox('a');
