### ISSUE TITLE
Lazy load thumbs

### ISSUE THREAD

**Issue by bostero2** [yairEO/photobox#89]
Hi is there a way of lazy loading the thumbnails? If not it could be a new feature to allow us to set an attribute for the code to get the image from (the one that is set on line 290). Right now I'm using data-src to lazy load the images on my site, but when I click on the images on the gallery the thumbnails are not displayed. If I manually change (I know that I shouldn't) the line 290 to take the "data-src" attribute it works perfectly. So the idea would be to add an option when calling the function to create the gallery where you can set the attribute to take the image for the thumb from.

Great work by the way, the gallery is really great and simple to use and customize... I was using slick slide but once I found this I HAD to switch and it really pays off, really great job!

**Comment by bostero2** [comment]
Created a pull request for this...

**Comment by yairEO** [comment]
I will fix this. The thumbnails are not in the scope of this plugin. Photobox is only about the "larger view" of a single photo and the way developers manage their gallery should be detached from the logic of this script in my opinion. I use https://github.com/yairEO/unveil to lazy-load images btw.
