### ISSUE TITLE
Unable to rebind same photobox element

### ISSUE THREAD

**Issue by themithrandir** [yairEO/photobox#91]
Good day. I am attempting to 'rebind' a previously bound html element to a new collection of images and then subsequently re-instantiate the photobox. I'm calling the 'destroy' method on the html element immediately before I'm attempting the re-instantiation, however the photobox is failing all subsequent re-instantiations. Please advise, thank you

**Comment by yairEO** [comment]
why would you rebind? you don't need to do that. there is no reason

**Comment by themithrandir** [comment]
I'm loading groups of thumbnails dynamically, based on a previously selected parent object. For example, the page loads with 10 buttons, each representing a different house. When the user clicks on one of the buttons, I make a web service call to get a list of photos of different rooms inside the house and bind the photobox to the list of photos. When the user clicks a different house button, I make another web service call to get the room photos for that house and that's where I"m attempting to "rebind" the existing photobox to the new collection of photos.

**Comment by yairEO** [comment]
you don't need to do that. photobox does everything automatically, just remove the `<a>` elements which you don't want from the DOM and add other ones, and everything will just work. have you tried that?

**Comment by themithrandir** [comment]
I have not tried that, I will attempt and let you know if it works. Thank you for your guidance!!

**Comment by yairEO** [comment]
well, how did it went?
