### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by AleMinato** [yairEO/photobox#93]
Sorry my Inglés is bad, i'm noob using plugins jquery, but I need your help , I do not get to photobox visualize, i click on the image not visualize, only the image locally opens.

**Comment by AleBes** [comment]
the same problem

**Comment by AleBes** [comment]
Plugin does not work out of the box?

**Comment by yairEO** [comment]
yes sir, what do you want me to do about it? come to your house and fix it for you?
please show me the code.

**Comment by AleMinato** [comment]
Im sorry, im a bit silly Ive realized that. Im using your main.js test,"your API Flickr ", i guess i should create my own API ; but what i do not understand how to put together my API with photobox? im beginning to learn JavaScript, and you yairEO man did a good job creating Photobox Css3.

If you can not help me, ill understand, im who I worry about my business and ill keep investigating elsewhere for use photobox.

I thank you for your attention.

**Comment by yairEO** [comment]
main.js is just for the a demo, it's not a part of the plugin. only what's inside the `photobox` folder is obviously the plugin. 

I can only help if I could see the code, but mind you that I do not help with cases unrelated to Photobox, which means anything that is not what's inside the folder I've mentioned above. 

Photobox is about showing a photo, a single photo. it's not a gallery plugin, it's just a viewer for a single photo.

**Comment by AleBes** [comment]
You've made the most beautiful plugin. But I couldn't figure out how it
works. I put 3 photos. What need to do? Help me please=)

2015-04-22 16:53 GMT+03:00 vsync <notifications@github.com>:

**Comment by yairEO** [comment]
what do you mean you don't know how to use it? 
The README is perfectly clear with simple instruction. you put links with `href` set to the big picture and inside them `img` tags with `src` pointing to low-res picture and then you bind photobox to those links. just look at the README. I cannot write more than what was already said there
