### ISSUE TITLE
Transition detecting

### ISSUE THREAD

**Issue by TrySound** [yairEO/photobox#97]
I recommend u to use this code for transition detecting
```js
var transition;
var transitionEnd;
(function () {
  var style = document.createElement('a').style;
  var prop;
  if(style[prop = 'webkitTransition'] === '') {
    transitionEnd = 'webkitTransitionEnd';
    transition = prop;
  }
  if(style[prop = 'transition'] === '') {
    transitionEnd = 'transitionend';
    transition = prop;
  }
} ());
```
You shouldn't use prefixed transition with IE, because it never was prefixed. Also Opera's prefix no needed.

[transition on caniuse](http://caniuse.com/#feat=css-transitions)

**Comment by TrySound** [comment]
To remove no needed prefixes use autoprefixer please. It uses strict caniuse database and makes better code than mixins.

**Comment by yairEO** [comment]
well what's wrong with the way I wrote it now? Thanks for letting me know the `ms` prefix in unneeded for `transitionend`, I check MDN and corrected this line to be:

    transitionend = "transitionend webkitTransitionEnd oTransitionEnd otransitionend"

To support old opera and remove the `ms` reference.

**Comment by TrySound** [comment]
12.1 Opera supports unprefixed transitions. Nobody use older opera.
And again code example overflows. Move comments to new line.

**Comment by TrySound** [comment]
Your way is bad, caz event fires twice on webkits. And instead of adding and removing listeners, you could add listener once. Better performance.

**Comment by TrySound** [comment]
And please remove `-ms-transition` from css code

**Comment by yairEO** [comment]
I removed the `-ms-transition` from the CSS, thanks. But regarding the `transitionend` event firing twice, I just checked on Chrome and it doesn't happen. I was sure jQuery is dealing with that internally.

**Comment by TrySound** [comment]
Yes. I checked too. It's old problem.

**Comment by TrySound** [comment]
But I still  recommend my way for less browser work and better performance.
